const routeData={adult:{title:"Из детства → во взрослость",note:"Не отвергать прошлое, а перестать жить только его правилами.",heroPath:"M95 735 C230 610 205 390 400 420 C535 442 510 245 710 250 C850 255 920 150 1080 185",preview:"M60 285 C210 210 180 90 360 115 C510 135 565 45 720 72 C835 92 875 55 950 60"},silence:{title:"Из шума → в тишину",note:"Не выключить весь мир, а различить в нём собственный голос.",heroPath:"M100 160 C250 120 270 330 410 320 C590 307 520 570 720 565 C890 560 880 390 1080 430",preview:"M55 80 C195 60 255 210 380 190 C520 170 530 310 700 280 C820 260 875 170 950 180"}};
const routeCards=[...document.querySelectorAll('.route-card')],routePath=document.getElementById('routePath'),previewPath=document.getElementById('previewPath'),routeTitle=document.getElementById('routeTitle'),routeNote=document.getElementById('routeNote');
function setRoute(key){const data=routeData[key];if(!data)return;routeCards.forEach(card=>card.classList.toggle('active',card.dataset.route===key));routePath.setAttribute('d',data.heroPath);previewPath.setAttribute('d',data.preview);routeTitle.textContent=data.title;routeNote.textContent=data.note}
routeCards.forEach(card=>{card.addEventListener('click',()=>setRoute(card.dataset.route));card.querySelector('.route-select')?.addEventListener('click',event=>{event.stopPropagation();setRoute(card.dataset.route);document.querySelector('.route-viewport')?.scrollIntoView({behavior:'smooth',block:'center'})})});
let jumpIndex=0;document.querySelector('[data-route-jump]')?.addEventListener('click',()=>{jumpIndex=(jumpIndex+1)%2;setRoute(jumpIndex?'silence':'adult');document.querySelector('.routes')?.scrollIntoView({behavior:'smooth',block:'start'})});
const focusPhrases=['то, что сейчас<br>важнее всего','то, что обычно<br>остаётся за кадром','место, где<br>появляется выбор'];let focusIndex=0;const camera=document.getElementById('camera'),focusSubject=document.getElementById('focusSubject');
function changeFocus(){focusIndex=(focusIndex+1)%focusPhrases.length;camera.classList.toggle('focus-2',focusIndex%2===1);focusSubject.style.opacity='0';setTimeout(()=>{focusSubject.innerHTML=focusPhrases[focusIndex];focusSubject.style.opacity='1'},180)}
document.querySelector('[data-focus]')?.addEventListener('click',changeFocus);
const tools=[...document.querySelectorAll('.tool-item')];const toolObserver=new IntersectionObserver(entries=>{entries.forEach(entry=>{if(entry.isIntersecting)tools.forEach(item=>item.classList.toggle('active',item===entry.target))})},{threshold:.62});tools.forEach(item=>toolObserver.observe(item));
const supportInput=document.getElementById('supportInput'),supportBtn=document.getElementById('supportBtn'),supportResult=document.getElementById('supportResult'),suggestions=document.getElementById('suggestions');
function showSupportResult(){if(!supportInput.value.trim()){supportInput.focus();supportInput.animate([{transform:'translateX(0)'},{transform:'translateX(-5px)'},{transform:'translateX(5px)'},{transform:'translateX(0)'}],{duration:260});return}supportResult.hidden=false;supportResult.scrollIntoView({behavior:'smooth',block:'nearest'})}
supportBtn?.addEventListener('click',showSupportResult);supportInput?.addEventListener('keydown',e=>{if(e.key==='Enter')showSupportResult()});suggestions?.querySelectorAll('button').forEach(button=>button.addEventListener('click',()=>{supportInput.value=button.textContent.trim();supportInput.focus()}));
document.getElementById('year').textContent=new Date().getFullYear();
